version: '3.8'
x-bot-environment:
  &bot-environment
  BOT_TOKEN: "${BOT_TOKEN}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASS: "${DB_PASS}"
  DB_HOST: "${DB_HOST}"

services:
  bot:
    build:
      context: .
    restart: unless-stopped
    environment: *bot-environment
